parameters:

services:

    ddr.rest.repository.access_token:
        class: Dontdrinkandroot\RestBundle\Repository\AccessTokenRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ '%ddr.rest.access_token_class%' ]

    ddr.rest.service.access_token:
        class: Dontdrinkandroot\RestBundle\Service\AccessTokenService
        arguments:
            - '@ddr.rest.repository.access_token'
            - '%ddr.rest.access_token_class%'
            - '@security.authentication.manager'
            - '%ddr.rest.authentication_provider_key%'

    ddr.rest.security.access_token_authenticator:
        class: Dontdrinkandroot\RestBundle\Security\DefaultAccessTokenAuthenticator
        arguments:
            - '@ddr.rest.repository.access_token'
        calls:
            - ['setTokenRequired', [false]]

    ddr_rest.metadata.driver.annotation:
        class: Dontdrinkandroot\RestBundle\Metadata\AnnotationDriver
        arguments:
            - '@annotation_reader'

    ddr_rest.metadata.factory:
        class: Metadata\MetadataFactory
        arguments:
            - '@ddr_rest.metadata.driver.annotation'

    ddr.rest.parser.request:
        class: Dontdrinkandroot\RestBundle\Service\RestRequestParser
        arguments:
            - '@ddr_rest.metadata.factory'
            - '@jms_serializer'
            - '@property_accessor'

    # We do not want serialization into underscored properties
    ddr.serializer.naming_strategy.identical_property_naming:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'
        public: false

    # Wrapping naming strategy into cached naming strategy for speed
    jms_serializer.naming_strategy:
        class: 'JMS\Serializer\Naming\CacheNamingStrategy'
        arguments:
            - '@ddr.serializer.naming_strategy.identical_property_naming'

    ddr_rest.routing.rest_entity_loader:
        class: Dontdrinkandroot\RestBundle\Routing\RestEntityLoader
        arguments:
            - '@file_locator'
            - '@ddr_rest.metadata.factory'
        tags:
            - { name: routing.loader }

    fos_rest.serializer.jms:
        class: Dontdrinkandroot\RestBundle\Serialization\JMSSerializerAdapter
        arguments:
            - '@jms_serializer.serializer'
            - '@ddr_rest.serialization.exclusion_strategy.includes'

    ddr_rest.serialization.exclusion_strategy.includes:
        class: Dontdrinkandroot\RestBundle\Serialization\IncludesExclusionStrategy
        arguments:
            - '@request_stack'
            - '@ddr_rest.metadata.factory'

    ddr_rest.listener.kernel_exception:
        class: Dontdrinkandroot\RestBundle\Listener\KernelExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
