parameters:

services:

    ddr_rest.metadata.file_locator:
        class: Metadata\Driver\FileLocator
        arguments:

    ddr_rest.metadata.driver.doctrine:
        class: Dontdrinkandroot\RestBundle\Metadata\Driver\DoctrineDriver
        arguments:
            - '@doctrine.orm.entity_manager'

    ddr_rest.metadata.driver.annotation:
        class: Dontdrinkandroot\RestBundle\Metadata\Driver\AnnotationDriver
        arguments:
            - '@annotation_reader'
            - '@ddr_rest.metadata.driver.doctrine'

    ddr_rest.metadata.driver.yaml:
        class: Dontdrinkandroot\RestBundle\Metadata\Driver\YamlDriver
        arguments:
            - '@ddr_rest.metadata.file_locator'
            - '@ddr_rest.metadata.driver.doctrine'

    ddr_rest.metadata.cache:
        class: Metadata\Cache\DoctrineCacheAdapter
        arguments:
            - 'ddr_rest'
            - '@doctrine.orm.default_metadata_cache'

    ddr_rest.metadata.driver.chain:
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@ddr_rest.metadata.driver.yaml', '@ddr_rest.metadata.driver.annotation']

    ddr_rest.metadata.factory:
        class: Metadata\MetadataFactory
        arguments:
            - '@ddr_rest.metadata.driver.chain'
        calls:
            - ['setCache',['@ddr_rest.metadata.cache']]

    ddr_rest.parser.request:
        class: Dontdrinkandroot\RestBundle\Service\RestRequestParser
        arguments:
            - '@ddr_rest.metadata.factory'
            - '@property_accessor'
            - '@doctrine.orm.entity_manager'
        calls:
            - [setAuthorizationChecker, ['@?security.authorization_checker']]

    ddr_rest.routing.rest_entity_loader:
        class: Dontdrinkandroot\RestBundle\Routing\RestResourceLoader
        arguments:
            - '@file_locator'
            - '@ddr_rest.metadata.factory'
            - 'ddr_rest.security.enabled'
        tags:
            - { name: routing.loader }

    ddr_rest.listener.kernel_exception:
        class: Dontdrinkandroot\RestBundle\Listener\KernelExceptionListener
        arguments:
            - '%ddr_rest.paths%'
        calls:
            - ['setDebug', ['%kernel.debug%']]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    ddr_rest.normalizer:
        class: Dontdrinkandroot\RestBundle\Service\Normalizer
        arguments:
            - '@ddr_rest.metadata.factory'
            - '@property_accessor'
            - '@router'

    ddr_rest.controller.doctrine:
        class: Dontdrinkandroot\RestBundle\Controller\DoctrineRestResourceController
        arguments:
            - '@ddr_rest.parser.request'
            - '@ddr_rest.normalizer'
            - '@validator'
            - '@request_stack'
            - '@ddr_rest.metadata.factory'
            - '@property_accessor'
            - '@doctrine.orm.entity_manager'
        calls:
            - [setAuthorizationChecker, ['@?security.authorization_checker']]
        public: true