parameters:

services:

    ddr_rest.metadata.file_locator:
        class: Metadata\Driver\FileLocator

    Dontdrinkandroot\RestBundle\Metadata\Driver\DoctrineDriver:
        arguments:
            - '@doctrine.orm.entity_manager'

    ddr_rest.metadata.driver.doctrine: '@Dontdrinkandroot\RestBundle\Metadata\Driver\DoctrineDriver'

    Dontdrinkandroot\RestBundle\Metadata\Driver\AnnotationDriver:
        arguments:
            - '@annotation_reader'
            - '@ddr_rest.metadata.driver.doctrine'

    ddr_rest.metadata.driver.annotation: '@Dontdrinkandroot\RestBundle\Metadata\Driver\AnnotationDriver'

    Dontdrinkandroot\RestBundle\Metadata\Driver\YamlDriver:
            - '@ddr_rest.metadata.file_locator'
            - '@ddr_rest.metadata.driver.doctrine'

    ddr_rest.metadata.driver.yaml: '@Dontdrinkandroot\RestBundle\Metadata\Driver\YamlDriver'

    ddr_rest.metadata.cache:
        class: Metadata\Cache\DoctrineCacheAdapter
        arguments:
            - 'ddr_rest'
            - '@doctrine.orm.default_metadata_cache'

    ddr_rest.metadata.driver.chain:
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@ddr_rest.metadata.driver.yaml', '@ddr_rest.metadata.driver.annotation']

    Dontdrinkandroot\RestBundle\Metadata\RestMetadataFactory:
        arguments:
            - '@ddr_rest.metadata.driver.chain'
        calls:
            - ['setCache',['@ddr_rest.metadata.cache']]

    ddr_rest.parser.request: '@Dontdrinkandroot\RestBundle\Service\RestRequestParser'

    ddr_rest.metadata.factory: '@Dontdrinkandroot\RestBundle\Metadata\RestMetadataFactory'

    Dontdrinkandroot\RestBundle\Service\RestRequestParser:
        arguments:
            - '@ddr_rest.metadata.factory'
            - '@property_accessor'
            - '@doctrine.orm.entity_manager'
        calls:
            - [setAuthorizationChecker, ['@?security.authorization_checker']]


    Dontdrinkandroot\RestBundle\Routing\RestResourceLoader:
        arguments:
            - '@file_locator'
            - '@ddr_rest.metadata.factory'
        tags:
            - { name: routing.loader }

    ddr_rest.routing.rest_entity_loader: '@Dontdrinkandroot\RestBundle\Routing\RestResourceLoader'


    Dontdrinkandroot\RestBundle\Listener\KernelExceptionListener:
        arguments:
            - '%ddr_rest.paths%'
        calls:
            - ['setDebug', ['%kernel.debug%']]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    ddr_rest.listener.kernel_exception: '@Dontdrinkandroot\RestBundle\Listener\KernelExceptionListener'

    Dontdrinkandroot\RestBundle\Service\Normalizer:
        arguments:
            - '@ddr_rest.metadata.factory'
            - '@property_accessor'
            - '@router'

    ddr_rest.normalizer: '@Dontdrinkandroot\RestBundle\Service\Normalizer'

    Dontdrinkandroot\RestBundle\Controller\DoctrineRestResourceController:
        arguments:
            - '@ddr_rest.parser.request'
            - '@ddr_rest.normalizer'
            - '@validator'
            - '@request_stack'
            - '@ddr_rest.metadata.factory'
            - '@property_accessor'
            - '@doctrine.orm.entity_manager'
        calls:
            - [setAuthorizationChecker, ['@?security.authorization_checker']]
        public: true

    ddr_rest.controller.doctrine:
        alias: 'Dontdrinkandroot\RestBundle\Controller\DoctrineRestResourceController'
        public: true