services:

    ddr_rest.repository.access_token:
        class: Dontdrinkandroot\RestBundle\Repository\AccessTokenRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ '%ddr_rest.access_token_class%' ]

    ddr_rest.service.access_token:
        class: Dontdrinkandroot\RestBundle\Service\AccessTokenService
        arguments:
            - '@ddr_rest.repository.access_token'
            - '%ddr_rest.access_token_class%'
            - '@security.authentication.manager'
            - '%ddr_rest.authentication_provider_key%'

    ddr_rest.security.access_token_authenticator:
        class: Dontdrinkandroot\RestBundle\Security\DefaultAccessTokenAuthenticator
        arguments:
            - '@ddr_rest.repository.access_token'
        calls:
            - ['setTokenRequired', [false]]

    ddr_rest.command.cleanup_access_tokens:
        class: Dontdrinkandroot\RestBundle\Command\CleanUpAccessTokensCommand
        arguments:
            - '@ddr_rest.service.access_token'
        tags:
            - { name: 'console.command', command: 'ddr:rest:access-token:cleanup' }

    ddr_rest.controller.access_token:
        class: Dontdrinkandroot\RestBundle\Controller\AccessTokenController
        arguments:
            - '@ddr_rest.service.access_token'
            - '@ddr_rest.parser.request'
            - '@ddr_rest.normalizer'
            - '@security.token_storage'
        public: true
