parameters:

services:

    ddr_rest.metadata.driver.doctrine:
        class: Dontdrinkandroot\RestBundle\Metadata\Driver\DoctrineDriver
        arguments:
            - '@doctrine.orm.entity_manager'

    ddr_rest.metadata.driver.annotation:
        class: Dontdrinkandroot\RestBundle\Metadata\Driver\AnnotationDriver
        arguments:
            - '@annotation_reader'
            - '@ddr_rest.metadata.driver.doctrine'

    ddr_rest.metadata.driver.chain:
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@ddr_rest.metadata.driver.annotation']


    ddr_rest.metadata.factory:
        class: Metadata\MetadataFactory
        arguments:
            - '@ddr_rest.metadata.driver.chain'

    ddr.rest.parser.request:
        class: Dontdrinkandroot\RestBundle\Service\RestRequestParser
        arguments:
            - '@ddr_rest.metadata.factory'

    ddr_rest.routing.rest_entity_loader:
        class: Dontdrinkandroot\RestBundle\Routing\RestEntityLoader
        arguments:
            - '@file_locator'
            - '@ddr_rest.metadata.factory'
        tags:
            - { name: routing.loader }

    ddr_rest.listener.kernel_exception:
        class: Dontdrinkandroot\RestBundle\Listener\KernelExceptionListener
        arguments:
            - '%ddr.rest.paths%'
        calls:
            - ['setDebug', ['%kernel.debug%']]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    ddr_rest.normalizer:
        class: Dontdrinkandroot\RestBundle\Service\Normalizer
        arguments:
            - '@ddr_rest.metadata.factory'