filter:
    excluded_paths: [Tests/*]
tools:
    external_code_coverage:
        timeout: 1200
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, test]
    php_loc:
        enabled: true
        excluded_dirs: [vendor, test]
    php_pdepend: true
    php_sim: true
