Dontdrinkandroot\RestBundle\Model\UserCredentials:
    fields:
        username:
            type: string
            postable: true
        password:
            type: string
            postable: true
